### ISSUE TITLE
Display The Nearest Bus Stop 0.4Km away in Current Position

### ISSUE THREAD

**Issue by josnin** [josnin/ng5-sgbus#7]
![image](https://user-images.githubusercontent.com/3206118/43356910-ad8bf2ce-92ab-11e8-8cff-1de629286941.png)

**Comment by joseninocapati** [comment]
May need this bec. geolcation will not work in not secured http
https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

Creating HTTPS development in angular

https://brianflove.com/2016/10/22/angular-cli-using-https/


How to create certifi and key in openssl

https://fedoraproject.org/wiki/Https
